#if !canImport(ObjectiveC)
import XCTest

extension AuthenticationCoordinatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthenticationCoordinatorTests = [
        ("testAnyMatcher", testAnyMatcher),
        ("testCaptureArgument", testCaptureArgument),
        ("testInstanceOf", testInstanceOf),
        ("testLogin", testLogin),
        ("testSetup", testSetup),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthenticationCoordinatorTests.__allTests__AuthenticationCoordinatorTests),
    ]
}
#endif
